# Generated by Django 4.2.4 on 2024-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_pedido_contato_alter_pedido_cpf_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrarProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=100)),
                ('produto', models.CharField(max_length=100)),
                ('descricao_produto', models.TextField(max_length=100)),
            ],
        ),
    ]
