# Generated by Django 4.2.4 on 2024-08-10 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_criarcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('cpf_cnpj', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11)])),
                ('contato', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10)])),
                ('end_empresa', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='criarcliente',
            name='contato',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='criarcliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='criarcliente',
            name='detal_cliente',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
        migrations.AlterField(
            model_name='criarcliente',
            name='nome_cliente',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
