# Generated by Django 4.2.4 on 2024-09-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pedido_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='vendedor',
        ),
    ]
