# Generated by Django 4.2.4 on 2024-09-14 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_pedido_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarcliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cpf_cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
