# Generated by Django 4.2.4 on 2024-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_cadastroempresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logomarca/'),
        ),
    ]
