# Generated by Django 4.2.4 on 2024-09-29 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_cadastroempresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarcliente',
            name='bairro',
            field=models.CharField(default='Bairro Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='criarcliente',
            name='cep',
            field=models.CharField(default='Bairro Desconhecido', max_length=9, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criarcliente',
            name='cidade',
            field=models.CharField(default='Cidade Desconhecida', max_length=100),
        ),
        migrations.AddField(
            model_name='criarcliente',
            name='estado',
            field=models.CharField(default='Estado Desconhecido', max_length=2),
        ),
        migrations.AddField(
            model_name='criarcliente',
            name='logradouro',
            field=models.CharField(default='Logradouro Desconhecido', max_length=255),
            preserve_default=False,
        ),
    ]
