# Generated by Django 4.2.4 on 2024-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_criarcliente_bairro_criarcliente_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criarcliente',
            name='numero',
            field=models.CharField(default='SN', max_length=20),
        ),
        migrations.AlterField(
            model_name='criarcliente',
            name='logradouro',
            field=models.CharField(default='Logradouro Desconhecido', max_length=255),
        ),
    ]
