# Generated by Django 4.2.4 on 2024-09-29 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_criarcliente_numero_alter_criarcliente_logradouro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criarcliente',
            name='detal_cliente',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='criarcliente',
            name='estado',
            field=models.CharField(default='NI', max_length=2),
        ),
    ]
