# Generated by Django 4.2.4 on 2024-09-29 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_criarcliente_detal_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroempresa',
            name='end_empresa',
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='bairro',
            field=models.CharField(default='Bairro Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='cep',
            field=models.CharField(default=0, max_length=9, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='cidade',
            field=models.CharField(default='Cidade Desconhecida', max_length=100),
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='estado',
            field=models.CharField(default='NI', max_length=2),
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='logradouro',
            field=models.CharField(default='Logradouro Desconhecido', max_length=255),
        ),
        migrations.AddField(
            model_name='cadastroempresa',
            name='numero',
            field=models.CharField(default='SN', max_length=20),
        ),
    ]
